[package]
name = "chronoclean"
version = "0.1.3"
edition = "2021"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
color-eyre = "0.6.5"
humantime = "2.3.0"
trash = "5.2.5"
walkdir = "2.5"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
debug = "line-tables-only"