[package]
name = "chronoclean"
version = "0.1.2"
edition = "2021"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
color-eyre = "0.6.3"
humantime = "2.2.0"
trash = "5.2.2"
walkdir = "2.5"

[profile.release]
opt-level = 3
lto = true
